# Site settings
title: Barlow Robotics
# email: 
description: > # this means to ignore newlines until "baseurl:"
  Joel Barlow Robotics team #4572.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://barlow-robotics.github.io" # the base hostname & protocol for your site
github_username: barlow-robotics

# Build settings
markdown: kramdown
